# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: self-hosted

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: code style check
        run: flake8 .\azure_pipeline\ 

      - name: Build Python Package
        run: |
          python setup.py sdist --formats=zip

      # Runs a single command using the runners shell
      - name: build the docker image
        run: |
          docker build -t fastapi${{ github.run_number }} . 
          echo GITHUB_RUN_NUMBER = ${GITHUB_RUN_NUMBER}

      # Runs a set of commands using the runners shell
      - name: show the image list
        run: |
          docker image list
          docker run -p 8080:80 fastapi${{ github.run_number }}

      - name: push the docker image to docker hub
        run: |
          echo push dokcer image to docker hub
