# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - app-myapp-0331-2-prod-ae

on:
  push:
    branches:
      - kenny_dev
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2



    - name: Build Python Package and Upload Artifact
      run: |
        python setup.py sdist --formats=zip
    # Upload the artifact
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: python-package
        path: dist/azure_pipeline-1.zip


    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://index.docker.io/v1/
        username: ${{ secrets.AzureAppService_ContainerUsername_8389f15673f1492395b2714ea560a2f4 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_34665b8f39bb42c2b15c8445ffa1b902 }}

    - name: Download artifact
      uses: actions/download-artifact@v3
      with:
        name: python-package
  
    - name: Copy artifact to Docker build context
      run: |
        cp dist/azure_pipeline-1.zip .

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: index.docker.io/mly219blueheart/azure_pipeline:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'app-myapp-0331-2-prod-ae'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_47833dbd88994494a982a4b9dc526e62 }}
        images: 'index.docker.io/mly219blueheart/azure_pipeline:${{ github.sha }}'
